import { SUMMARY_SECTIONS } from '../ai/AIProvider'
import type { ExportSource } from './formats'

/**
 * The meeting as a standalone HTML document.
 *
 * Feeds two exports. PDF goes through Electron's `printToPDF`, which renders a
 * real page in a real WebContents — no PDF library, no layout engine of our
 * own, and the output matches what a browser would print. Word consumes the
 * same string, because .docx readers accept HTML.
 *
 * Written by hand rather than by reusing the renderer's React components: those
 * are styled with Tailwind utilities against CSS custom properties that only
 * exist inside the app's stylesheet, and a document leaving the app has to
 * carry its own styling. It also has to be readable in fifty years, which
 * argues for boring HTML.
 */

/**
 * Escape everything that comes from outside.
 *
 * Titles are user text and summaries are model output arriving over the
 * network. Neither is trusted, and this string is about to be loaded into a
 * WebContents — the one place in this app where an unescaped `<script>` would
 * actually execute. Applied to every interpolation without exception, so there
 * is no per-call judgement to get wrong.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/**
 * The same Markdown subset the renderer supports, as HTML.
 *
 * Escaping happens FIRST and the tags are added afterwards, so model output
 * cannot introduce markup — by the time a `<strong>` is inserted, any `<` in
 * the source is already `&lt;`.
 */
function inlineMarkdown(text: string): string {
  return escapeHtml(text)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*\n]+)\*/g, '<em>$1</em>')
    .replace(/_([^_\n]+)_/g, '<em>$1</em>')
}

/** Blocks, matching `Markdown.tsx`: bullet runs become lists, the rest paragraphs. */
function blockMarkdown(src: string): string {
  const out: string[] = []
  let list: string[] = []
  let para: string[] = []

  const flushList = (): void => {
    if (list.length === 0) return
    out.push(`<ul>${list.map((i) => `<li>${inlineMarkdown(i)}</li>`).join('')}</ul>`)
    list = []
  }
  const flushPara = (): void => {
    if (para.length === 0) return
    out.push(`<p>${para.map(inlineMarkdown).join('<br>')}</p>`)
    para = []
  }

  for (const raw of src.split('\n')) {
    const line = raw.trimEnd()
    if (line.trim() === '') {
      flushList()
      flushPara()
      continue
    }
    const bullet = /^\s*[-*+]\s+(.*)$/.exec(line)
    if (bullet) {
      flushPara()
      list.push(bullet[1] ?? '')
    } else {
      flushList()
      para.push(line)
    }
  }
  flushList()
  flushPara()
  return out.join('\n')
}

export interface HtmlOptions {
  /** Append the full transcript below the notes. */
  includeTranscript: boolean
}

export function toHtml(src: ExportSource, opts: HtmlOptions): string {
  const { meta, notes, transcript } = src

  const date = new Date(meta.startedAt)
  const when = Number.isNaN(date.getTime())
    ? ''
    : date.toLocaleString(undefined, {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
      })
  const minutes = Math.round(meta.durationSeconds / 60)

  const body: string[] = [
    `<h1>${escapeHtml(meta.title)}</h1>`,
    `<p class="meta">${escapeHtml(when)} · ${minutes < 1 ? 'under a minute' : `${minutes} min`}</p>`,
  ]

  const userNotes = notes.userNotes.trim()
  if (userNotes) body.push('<h2>My notes</h2>', blockMarkdown(userNotes))

  for (const section of SUMMARY_SECTIONS) {
    const text = notes.summary[section]?.trim()
    if (text) body.push(`<h2>${escapeHtml(section)}</h2>`, blockMarkdown(text))
  }

  if (opts.includeTranscript && transcript && transcript.segments.length > 0) {
    body.push('<h2 class="page-break">Transcript</h2>')
    for (const s of transcript.segments) {
      const name = s.speakerLabel ?? (s.speaker === 'me' ? 'Me' : 'Them')
      body.push(
        `<p class="turn"><span class="who ${s.speaker}">${escapeHtml(name)}</span>` +
          `<span class="text">${escapeHtml(s.text)}</span></p>`,
      )
    }
  }

  if (notes.provider) {
    body.push(
      `<p class="provenance">Summary generated by ${escapeHtml(notes.provider)}` +
        `${notes.generatedAt ? ` on ${escapeHtml(new Date(notes.generatedAt).toLocaleString())}` : ''}. ` +
        'Transcribed locally by Oratio.</p>',
    )
  }

  /*
   * Print styling, deliberately light.
   *
   * System fonts only — an exported document must not depend on a network
   * fetch, and `printToPDF` would render a fallback face without saying so.
   * Colours are fixed rather than themed: this file leaves the app, and a
   * document that renders differently depending on the appearance setting of
   * the machine that made it is a document with a bug.
   */
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(meta.title)}</title>
<style>
  @page { margin: 18mm 16mm; }
  body {
    font: 11pt/1.55 -apple-system, "SF Pro Text", system-ui, sans-serif;
    color: #1a1a1a;
    max-width: 42em;
    margin: 0 auto;
  }
  h1 { font-size: 19pt; margin: 0 0 0.15em; }
  h2 {
    font-size: 12pt;
    margin: 1.6em 0 0.5em;
    padding-bottom: 0.25em;
    border-bottom: 1px solid #ddd;
  }
  /* Keep a heading with the text it introduces rather than alone at a page
     foot — the one print rule worth spending a line on. */
  h1, h2 { break-after: avoid; }
  p { margin: 0 0 0.7em; orphans: 2; widows: 2; }
  ul { margin: 0 0 0.7em; padding-left: 1.3em; }
  li { margin-bottom: 0.25em; }
  code { font-family: "SF Mono", ui-monospace, monospace; font-size: 0.9em; }
  .meta { color: #666; font-size: 9.5pt; margin-bottom: 1.5em; }
  .page-break { break-before: page; }
  .turn { display: flex; gap: 0.7em; margin-bottom: 0.45em; break-inside: avoid; }
  .who {
    flex: 0 0 4.2em;
    font-size: 8.5pt;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    padding-top: 0.25em;
  }
  /* Same two-accent split the app uses, so a printed transcript is read the
     same way as the one on screen. Distinguishable in greyscale. */
  .who.me { color: #2f5fd0; }
  .who.them { color: #9a6512; }
  .text { flex: 1; }
  .provenance {
    margin-top: 2.5em;
    padding-top: 0.8em;
    border-top: 1px solid #ddd;
    color: #666;
    font-size: 9pt;
    font-style: italic;
  }
</style>
</head>
<body>
${body.join('\n')}
</body>
</html>`
}
